import "@/app/globals.css";
import { Inter } from "next/font/google";
import Style from "@/app/page.module.css"
import MyMenu from "@/components/molecules/my-menu/my-menu"
import { NextIntlClientProvider } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "fr" }];
}

export const metadata = {
  title: "TP-3 Integration",
  description: "Generated by create next app",
};

interface LayoutParams {
  locale: string;
}

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: LayoutParams;
}) {

  let translations;
  try {
    translations = (await import(`@/languages/${params.locale}.json`)).default;
  } catch (error) {
    translations = (await import(`@/languages/fr.json`)).default;
  }

  return (
    <html lang={params.locale}>
      <body>
        <NextIntlClientProvider locale={params.locale} messages={translations}>
          <main className={Style.main_container}>
            <MyMenu />
            {children}
          </main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

