import "@/app/globals.css";
import Style from "@/app/page.module.css"
import { Inter } from "next/font/google";
import MyMenu from "@/components/molecules/my-menu/my-menu";
import ApplicationProvider from "@/context/application.provider";
import { NextIntlClientProvider } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "fr" }];
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutParams {
  locale: string;
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: LayoutParams;
}) {
  let translations;
  try {
    translations = (await import(`../../languages/${params.locale}.json`))
      .default;
  } catch (error) {
    translations = (await import(`../../languages/en.json`)).default;
  }

  return (
    <html lang={params.locale}>
      <body>
        <NextIntlClientProvider locale={params.locale} messages={translations}>
          <ApplicationProvider>
            <div>
              <MyMenu />
              <main className={Style.main_container}>
                {children}
              </main>
            </div>
          </ApplicationProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}